ustomer value requires joining orders

CREATE OR REPLACE TABLE DATABASE3.GOLD.FACT_CUSTOMER_METRICS AS
SELECT
    C."id" AS CUSTOMER_ID,
    COUNT(O.ID) AS TOTAL_ORDERS,
    COALESCE(SUM(O.TOTAL), 0) AS LIFETIME_VALUE,
    MAX(C.CREATED_DATE) AS LAST_ORDER_DATE,
    CASE
        WHEN COUNT(O.ID) = 0 THEN 'Inactive'
        WHEN DATEDIFF('day', MAX(C.CREATED_DATE), CURRENT_DATE) > 90 THEN 'Churned'
        ELSE 'Active'
    END AS CUSTOMER_STATUS
FROM DATABASE3.SILVER.CUSTOMERS C
LEFT JOIN DATABASE3.SILVER.ORDERS O
    ON C."id" = O.CUSTOMER_ID
GROUP BY C."id";

SELECT * FROM DATABASE3.GOLD.fact_customer_metrics;